"""
Mechanical piping basis of design — the fifth and final discipline in the
agreed order (civils -> structural -> LV electrical -> HV electrical ->
mechanical piping). Scoped to industrial/plant process piping, consistent
with the access-steelwork/electrical scope of the other disciplines (not
domestic/commercial building services pipework).

Governing piping code kept generic, per project direction: both **ASME
B31.3** (Process Piping) and **BS EN 13480** (Metallic industrial piping) are
listed as applicable in `design_standards_and_criteria` rather than
committing to one — the specific project/client/jurisdiction decides which
governs, and a design may need to demonstrate compliance with either
depending on where the plant sits and who the client is.

*** Verify before real use *** — same caveat as every other basis_of_design
module in this repo: the standards below are populated from training
knowledge of commonly-cited piping codes/standards, not verified against
current purchased standard texts in this environment. Treat this as a
credible starting checklist, not a guaranteed-current authoritative list.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from basis_of_design.core import BasisOfDesignSection, CalculationRequirement, Interface, Standard
from core.risk import DesignRiskFlag

MECHANICAL_PIPING_SECTION_NAMES = [
    "design_standards_and_criteria",
    "pipe_sizing_and_flow",
    "pipe_stress_analysis_and_supports",
    "material_selection_and_corrosion",
    "valves_and_specialty_items",
    "flanges_gaskets_and_bolting",
    "pressure_testing_and_inspection",
    "insulation_and_heat_tracing",
    "supports_structural_and_hazardous_area_interfaces",
]


class MechanicalPipingBasisOfDesign(BaseModel):
    project_reference: Optional[str] = Field(None, description="Links to portfolio.models.Project.reference.")

    design_standards_and_criteria: BasisOfDesignSection
    pipe_sizing_and_flow: BasisOfDesignSection
    pipe_stress_analysis_and_supports: BasisOfDesignSection
    material_selection_and_corrosion: BasisOfDesignSection
    valves_and_specialty_items: BasisOfDesignSection
    flanges_gaskets_and_bolting: BasisOfDesignSection
    pressure_testing_and_inspection: BasisOfDesignSection
    insulation_and_heat_tracing: BasisOfDesignSection
    supports_structural_and_hazardous_area_interfaces: BasisOfDesignSection

    def sections(self) -> dict[str, BasisOfDesignSection]:
        return {name: getattr(self, name) for name in MECHANICAL_PIPING_SECTION_NAMES}


def build_mechanical_piping_bod_skeleton(project_reference: Optional[str] = None) -> MechanicalPipingBasisOfDesign:
    """
    Structurally complete MechanicalPipingBasisOfDesign. Criteria, assumptions,
    exclusions, and deliverables left empty for the detail pass.
    """
    return MechanicalPipingBasisOfDesign(
        project_reference=project_reference,
        design_standards_and_criteria=BasisOfDesignSection(
            name="Design standards and general criteria",
            scope=(
                "Overarching piping design basis: governing piping code, design conditions "
                "(pressure/temperature), pressure equipment regulatory regime, and pipeline "
                "class/category. Kept generic across governing code per project direction — "
                "both ASME B31.3 and BS EN 13480 are listed; the specific project/client/"
                "jurisdiction determines which actually governs."
            ),
            standards=[
                Standard(code="ASME B31.3", title="Process Piping"),
                Standard(code="BS EN 13480", title="Metallic industrial piping (all parts)", national_annex="UK NA where applicable"),
                Standard(code="PED 2014/68/EU", title="Pressure Equipment Directive", notes="EU — confirm applicability."),
                Standard(code="Pressure Equipment (Safety) Regulations 2016", notes="UK implementation of PED post-Brexit."),
                Standard(code="Pressure Systems Safety Regulations 2000", notes="UK — in-service written scheme of examination requirement."),
            ],
        ),
        pipe_sizing_and_flow=BasisOfDesignSection(
            name="Pipe sizing and flow",
            scope="Line sizing from process flow/velocity criteria, pressure drop, and erosional velocity limits.",
            standards=[
                Standard(code="API RP 14E", notes="Erosional velocity guidance — confirm applicability outside oil & gas context."),
            ],
            interfaces=[
                Interface(with_discipline="process", description="Line sizing is driven by process flow data/P&IDs — assumed available as an input, not generated by this discipline."),
            ],
            calculations_required=[
                CalculationRequirement(name="Line sizing / velocity check", description="Pipe internal diameter from flow rate against velocity and pressure drop limits."),
            ],
        ),
        pipe_stress_analysis_and_supports=BasisOfDesignSection(
            name="Pipe stress analysis and supports",
            scope="Flexibility/stress analysis (thermal expansion, sustained and occasional loads), and support type/spacing.",
            standards=[
                Standard(code="ASME B31.3", notes="Stress analysis provisions — shared with design_standards_and_criteria."),
                Standard(code="BS EN 13480-3", title="Design and calculation"),
                Standard(code="MSS SP-58", title="Pipe hangers and supports", notes="Confirm current edition."),
            ],
            interfaces=[
                Interface(with_discipline="structural", description="Pipe support loads (dead, thermal, occasional) are applied loads on the supporting steelwork — see basis_of_design/structural.py."),
            ],
            calculations_required=[
                CalculationRequirement(name="Pipe flexibility/stress analysis", standard_reference="ASME B31.3"),
                CalculationRequirement(name="Support load schedule", description="Loads passed to the structural discipline per support point."),
            ],
            risk_flags=[
                DesignRiskFlag(
                    category="temporary_works",
                    severity="medium",
                    description=(
                        "Pipework is often erected in spans before its permanent supports are all "
                        "installed, and can be temporarily supported or left partially unsupported "
                        "during construction/tie-in — a condition the completed stress analysis "
                        "(which assumes all permanent supports in place) does not itself cover."
                    ),
                    trigger="Any piping section installed progressively, or requiring temporary support/blinding during tie-ins.",
                    recommended_action="Contractor/temporary works designer to verify temporary support adequacy for the actual construction sequence, not just the as-designed permanent support arrangement.",
                    source_reference="basis_of_design.mechanical_piping:pipe_stress_analysis_and_supports",
                ),
            ],
        ),
        material_selection_and_corrosion=BasisOfDesignSection(
            name="Material selection and corrosion",
            scope="Pipe/fitting material selection, corrosion allowance, and any material-specific service restrictions (e.g. sour service).",
            standards=[
                Standard(code="ASME B36.10M", title="Welded and Seamless Wrought Steel Pipe"),
                Standard(code="ISO 21457", title="Materials selection for oil and gas production systems", notes="Confirm applicability outside oil & gas."),
                Standard(code="NACE MR0175 / ISO 15156", notes="Sour service material requirements — only where applicable to the process fluid."),
            ],
        ),
        valves_and_specialty_items=BasisOfDesignSection(
            name="Valves and specialty items",
            scope="Valve type/rating selection, actuation, and specialty items (strainers, steam traps, expansion joints, relief devices).",
            standards=[
                Standard(code="API 6D", title="Specification for Pipeline and Piping Valves", notes="Confirm applicability outside pipeline context."),
                Standard(code="BS EN 12266", title="Industrial valves — testing"),
                Standard(code="ASME B16.34", title="Valves — Flanged, Threaded, and Welding End"),
            ],
        ),
        flanges_gaskets_and_bolting=BasisOfDesignSection(
            name="Flanges, gaskets and bolting",
            scope="Flange rating/facing selection, gasket type, and bolting specification/torque.",
            standards=[
                Standard(code="ASME B16.5", title="Pipe Flanges and Flanged Fittings"),
                Standard(code="BS EN 1092-1", title="Flanges and their joints — Circular flanges for pipes"),
                Standard(code="BS EN 1591-1", title="Flanges and their joints — Design rules for gasketed circular flange connections"),
            ],
        ),
        pressure_testing_and_inspection=BasisOfDesignSection(
            name="Pressure testing and inspection",
            scope="Hydrostatic/pneumatic test requirements, NDT scope, and in-service inspection/written scheme of examination basis.",
            standards=[
                Standard(code="ASME B31.3", notes="Test pressure provisions — shared with design_standards_and_criteria."),
                Standard(code="BS EN 13480-5", title="Inspection and testing"),
                Standard(code="ASME BPVC Section V / BS EN ISO 17636", notes="Non-destructive examination — confirm which set governs per the chosen piping code."),
                Standard(code="Pressure Systems Safety Regulations 2000", notes="Written scheme of examination for in-service inspection — shared with design_standards_and_criteria."),
            ],
            risk_flags=[
                DesignRiskFlag(
                    category="safety",
                    severity="high",
                    description=(
                        "Hydrostatic/pneumatic pressure testing is itself a distinct hazardous "
                        "activity (stored energy, test rig/blind flange failure, exclusion zone "
                        "requirements) separate from the completed system's normal operating risk, "
                        "and is easy to under-specify if only the permanent design condition is considered."
                    ),
                    trigger="Any new or modified pressure system requires a pre-service pressure test.",
                    recommended_action="Define test method (hydro preferred over pneumatic where practicable), test pressure/duration, exclusion zone, and temporary test equipment (blinds, gauges) explicitly before construction.",
                    source_reference="basis_of_design.mechanical_piping:pressure_testing_and_inspection",
                ),
            ],
        ),
        insulation_and_heat_tracing=BasisOfDesignSection(
            name="Insulation and heat tracing",
            scope="Thermal/personnel-protection insulation selection and electrical or steam trace heating design.",
            standards=[
                Standard(code="BS 5970", title="Thermal insulation of pipework and equipment", notes="Confirm current edition."),
                Standard(code="IEEE 515 / BS EN 60079-30", notes="Electrical trace heating — BS EN 60079-30 applies specifically where trace heating is in a classified hazardous area."),
            ],
            interfaces=[
                Interface(with_discipline="electrical_lv", description="Electrical trace heating circuits are LV small power/containment items, and must respect hazardous area classification where applicable."),
            ],
        ),
        supports_structural_and_hazardous_area_interfaces=BasisOfDesignSection(
            name="Supports, structural interface, and hazardous area interface",
            scope=(
                "Cross-discipline interface section: pipe rack/support steelwork coordination "
                "with structural, and confirmation that piping/equipment layout and any "
                "electrical items (trace heating, instrumentation) are consistent with the "
                "hazardous area classification set by the electrical discipline."
            ),
            interfaces=[
                Interface(with_discipline="structural", description="Pipe racks and major support steelwork are designed/detailed under basis_of_design/structural.py, loaded from this discipline."),
                Interface(with_discipline="electrical_lv", description="Hazardous area classification (basis_of_design/electrical_lv.py) constrains equipment selection for any electrical items on or near piping (trace heating, instruments, valve actuators)."),
                Interface(with_discipline="civils", description="Below-ground/buried piping routes coordinated with civils utilities coordination and earthworks."),
            ],
            risk_flags=[
                DesignRiskFlag(
                    category="code_compliance",
                    severity="high",
                    description=(
                        "Piping layout, equipment, and any associated electrical items are at risk "
                        "of being specified before hazardous area classification is finalised, "
                        "mirroring the same sequencing risk flagged in the LV electrical basis of "
                        "design — this section exists specifically to force that check at the "
                        "piping/electrical boundary rather than leaving it implicit."
                    ),
                    trigger="Any piping system handling a flammable/combustible fluid, or routed through a classified area.",
                    recommended_action="Confirm hazardous area classification is complete and referenced before finalising equipment selection for any electrical item associated with the piping system.",
                    source_reference="basis_of_design.mechanical_piping:supports_structural_and_hazardous_area_interfaces",
                ),
            ],
        ),
    )


if __name__ == "__main__":
    # python3 -m basis_of_design.mechanical_piping  -- prints the skeleton BoD as markdown.
    from basis_of_design.render import render_basis_of_design

    bod = build_mechanical_piping_bod_skeleton()
    print(render_basis_of_design("Mechanical Piping", bod.sections()))
